"""station catalog and measured observations

Revision ID: 3b6f82078bcf
Revises: 5f0e7c29b4a1
Create Date: 2026-10-05 20:20:20.701838
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3b6f82078bcf"
down_revision: str | None = "5f0e7c29b4a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_stations",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "latitude IS NULL OR latitude BETWEEN -90 AND 90", name="ck_station_lat"
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180", name="ck_station_lon"
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index("ix_stations_state_name", "weather_stations", ["state", "name"], unique=False)
    op.create_table(
        "station_observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("station_code", sa.String(length=16), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period", sa.String(length=10), nullable=False),
        sa.Column("temperature_c", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("minimum_c", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("maximum_c", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("humidity", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("precipitation_mm", sa.Numeric(precision=9, scale=2), nullable=True),
        sa.Column("wind_ms", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "period IN ('HOURLY', 'DAILY', 'MONTHLY')", name="ck_observation_period"
        ),
        sa.CheckConstraint(
            "humidity IS NULL OR humidity BETWEEN 0 AND 100", name="ck_observation_humidity"
        ),
        sa.CheckConstraint(
            "precipitation_mm IS NULL OR precipitation_mm >= 0", name="ck_observation_rain"
        ),
        sa.CheckConstraint("wind_ms IS NULL OR wind_ms >= 0", name="ck_observation_wind"),
        sa.ForeignKeyConstraint(["station_code"], ["weather_stations.code"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("station_code", "observed_at", "period", name="uq_station_observation"),
    )
    op.create_index("ix_observations_time", "station_observations", ["observed_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_observations_time", table_name="station_observations")
    op.drop_table("station_observations")
    op.drop_index("ix_stations_state_name", table_name="weather_stations")
    op.drop_table("weather_stations")
    # ### end Alembic commands ###
