"""initial schema

Revision ID: b6f535f44c51
Revises:
Create Date: 2026-09-15 09:29:01.427998
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b6f535f44c51"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_code", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("weather_notifications", sa.Boolean(), nullable=False),
        sa.Column("alert_sound", sa.Boolean(), nullable=False),
        sa.Column("dark_theme", sa.Boolean(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(latitude IS NULL AND longitude IS NULL) OR "
            "(latitude IS NOT NULL AND longitude IS NOT NULL)",
            name="ck_user_coordinates_pair",
        ),
        sa.CheckConstraint("latitude IS NULL OR latitude BETWEEN -90 AND 90", name="ck_user_lat"),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180", name="ck_user_lon"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("public_code"),
    )
    op.create_index("ix_users_name", "users", ["name"], unique=False)
    op.create_index("ix_users_role_id", "users", ["role_id"], unique=False)
    op.create_table(
        "educational_contents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_key", sa.String(length=80), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("media_url", sa.String(length=500), nullable=True),
        sa.Column("reference_url", sa.String(length=500), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_key"),
    )
    op.create_index(
        "ix_education_published", "educational_contents", ["published_at"], unique=False
    )
    op.create_table(
        "forecasts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_key", sa.String(length=80), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("condition", sa.String(length=120), nullable=False),
        sa.Column("temperature_c", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("minimum_c", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("maximum_c", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("humidity", sa.Integer(), nullable=False),
        sa.Column("wind_kmh", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("rain_probability", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("polygon", sa.JSON(), nullable=True),
        sa.Column("source_name", sa.String(length=120), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("humidity BETWEEN 0 AND 100", name="ck_forecast_humidity"),
        sa.CheckConstraint("rain_probability BETWEEN 0 AND 100", name="ck_forecast_rain"),
        sa.CheckConstraint("valid_until > issued_at", name="ck_forecast_validity"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_key"),
    )
    op.create_index(
        "ix_forecasts_location_valid", "forecasts", ["city", "state", "valid_until"], unique=False
    )
    op.create_table(
        "news",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_news_published", "news", ["published_at"], unique=False)
    op.create_table(
        "weather_alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_key", sa.String(length=80), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=140), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("area_name", sa.String(length=160), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("radius_km", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("polygon", sa.JSON(), nullable=True),
        sa.Column("recommendations", sa.JSON(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("latitude IS NULL OR latitude BETWEEN -90 AND 90", name="ck_alert_lat"),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180", name="ck_alert_lon"
        ),
        sa.CheckConstraint(
            "(latitude IS NULL AND longitude IS NULL) OR "
            "(latitude IS NOT NULL AND longitude IS NOT NULL)",
            name="ck_alert_coordinates_pair",
        ),
        sa.CheckConstraint("radius_km IS NULL OR radius_km > 0", name="ck_alert_radius"),
        sa.CheckConstraint(
            "polygon IS NOT NULL OR "
            "(latitude IS NOT NULL AND longitude IS NOT NULL AND radius_km IS NOT NULL)",
            name="ck_alert_has_area",
        ),
        sa.CheckConstraint(
            "severity IN ('LOW', 'MODERATE', 'HIGH', 'CRITICAL')",
            name="ck_alert_severity",
        ),
        sa.CheckConstraint("valid_until > issued_at", name="ck_alert_validity"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_key"),
    )
    op.create_index("ix_alerts_active", "weather_alerts", ["valid_until", "severity"], unique=False)
    if op.get_bind().dialect.name == "mysql":
        op.execute(
            "CREATE TRIGGER weather_alerts_no_update BEFORE UPDATE ON weather_alerts "
            "FOR EACH ROW SIGNAL SQLSTATE '45000' "
            "SET MESSAGE_TEXT = 'Issued weather alerts are immutable'"
        )
        op.execute(
            "CREATE TRIGGER weather_alerts_no_delete BEFORE DELETE ON weather_alerts "
            "FOR EACH ROW SIGNAL SQLSTATE '45000' "
            "SET MESSAGE_TEXT = 'Issued weather alerts cannot be deleted'"
        )
    op.create_table(
        "weather_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("reporter_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name="ck_report_lat"),
        sa.CheckConstraint("longitude BETWEEN -180 AND 180", name="ck_report_lon"),
        sa.CheckConstraint(
            "status IN ('PENDING', 'APPROVED', 'REJECTED')", name="ck_report_status"
        ),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_reports_review_queue", "weather_reports", ["status", "created_at"], unique=False
    )
    op.create_index(
        "ix_reports_reporter_created",
        "weather_reports",
        ["reporter_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "alert_reads",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["alert_id"], ["weather_alerts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "alert_id", name="uq_alert_read_user_alert"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alert_reads")
    op.drop_index("ix_reports_reporter_created", table_name="weather_reports")
    op.drop_index("ix_reports_review_queue", table_name="weather_reports")
    op.drop_table("weather_reports")
    op.drop_index("ix_alerts_active", table_name="weather_alerts")
    op.drop_table("weather_alerts")
    op.drop_index("ix_news_published", table_name="news")
    op.drop_table("news")
    op.drop_index("ix_forecasts_location_valid", table_name="forecasts")
    op.drop_table("forecasts")
    op.drop_index("ix_education_published", table_name="educational_contents")
    op.drop_table("educational_contents")
    op.drop_index("ix_users_role_id", table_name="users")
    op.drop_index("ix_users_name", table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    # ### end Alembic commands ###
